PenaltyCalculation/Controllers/PenaltyCalculationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PenaltyCalculation.Models;
using PenaltyCalculation.Service;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace PenaltyCalculation.Controllers
{
    public class PenaltyCalculationController : Controller
    {
        private readonly IProcessingService _context;
        public PenaltyCalculationController(IProcessingService processingService)
        {
            _context = processingService;
        }
        public IActionResult Index()
        {
            var countries = _context.GetAllCountries();
            var model = new CalculationModel();
            model.ReturnedDate = DateTime.Now.Date;
            model.CheckedOutDate = DateTime.Now.Date;
            foreach (var item in countries)
                model.Countries.Add(new SelectListItem { Text = item.CountryName, Value = item.Id.ToString() });

            return View(model);
        }

        [HttpPost]
        public IActionResult CalculatePenalty(CalculationModel model)
        {
            var checkedOutDate = model.CheckedOutDate;
            var returnedDate = model.ReturnedDate.AddDays(1);

            var betweenDates = new List<DateTime>();


            while (checkedOutDate != returnedDate)
            {
                betweenDates.Add(checkedOutDate);
                checkedOutDate = checkedOutDate.AddDays(1);
            }

            var countryOffdays = _context.GetOffDaysByCountryId(model.SelectedCountryId);
            var publicHoldiays = _context.GetAllHolidaysByCountryId(model.SelectedCountryId);

            var penaltyDates = new List<DateTime>();
            foreach (var date in betweenDates)
            {
                var dateIsOff = countryOffdays.Any(x => date.ToString("dddd", new CultureInfo("en-GB")) == x.OffWeekDay.ToString());
                if (dateIsOff)
                    continue;

                var dateIsPublic = publicHoldiays.Any(x => date == x.HolidayDate.Date);
                if (dateIsPublic)
                    continue;

                penaltyDates.Add(date);
            }
            var selectedCountry = _context.GetCountryById(model.SelectedCountryId);
            var resultModel = new ResultModel
            {
                CountryName = selectedCountry.CountryName,
                CountryCurrencyName = selectedCountry.CountryCurrencyName,
                CountryCurrencyValue = selectedCountry.CountryCurrencyValue

            };
            if (penaltyDates.Count > 10)
            {
                resultModel.PenaltyPrize = penaltyDates.Count * 5 * selectedCountry.CountryCurrencyValue;
                resultModel.Message = penaltyDates.Count+" Days Penalty = ";
                resultModel.PenaltyDate = penaltyDates;
            }
            else
                resultModel.Message = "There is No Penalty";
            return View("Result", resultModel);

        }

    }
}

PenaltyCalculation/Controllers/PublicHolidayController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PenaltyCalculation.Models;
using PenaltyCalculation.Service;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PenaltyCalculation.Controllers
{
    public class PublicHolidayController : Controller
    {
        private readonly IProcessingService _context;
        public PublicHolidayController(IProcessingService processingService)
        {
            _context = processingService;
        }
    
        public IActionResult Index()
        {
            var countries = _context.GetAllCountries();
            var model = new PublicHolidayModel();
            foreach (var item in countries)
                model.Countries.Add(new SelectListItem { Text = item.CountryName, Value = item.Id.ToString() });
            return View("Index", model);
        }
        [HttpPost]
        public IActionResult Holiday(PublicHolidayModel model)
        {
            var publicHoldiays = _context.GetAllHolidaysByCountryId(model.SelectedCountryId);
            var publicHolidaysDate = new List<DateTime>();
            foreach (var item in publicHoldiays)
            {
                publicHolidaysDate.Add(item.HolidayDate);
            }
            model.PublicHolidays = publicHolidaysDate;
            return View("PublicHolidayView", model);
        }
       

    }
}

PenaltyCalculation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PenaltyCalculation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        $(".form_datetime").datetimepicker({ format: 'yyyy-mm-dd' });
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PenaltyCalculation</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PenaltyCalculation" asp-action="Index">Calculate</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PublicHoliday" asp-action="Index">Public Holidays</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3" align="center">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PenaltyCalculation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>